// Package pb contains the protobuf message types for the auth service.
// In production these structs are generated by protoc-gen-go.
// This hand-authored version is structurally equivalent and allows the service
// to compile without the protoc toolchain in CI.
package pb

// ── Auth messages ─────────────────────────────────────────────────────────────

type RegisterRequest struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Nickname  string `json:"nickname"`
	Password  string `json:"password"`
	Email     string `json:"email"`
	Country   string `json:"country"`
}

func (r *RegisterRequest) GetFirstName() string { return r.FirstName }
func (r *RegisterRequest) GetLastName() string  { return r.LastName }
func (r *RegisterRequest) GetNickname() string  { return r.Nickname }
func (r *RegisterRequest) GetPassword() string  { return r.Password }
func (r *RegisterRequest) GetEmail() string     { return r.Email }
func (r *RegisterRequest) GetCountry() string   { return r.Country }

// RegisterResponse includes the Zookie of the write so callers can anchor
// subsequent GetUser calls to this exact commit.
type RegisterResponse struct {
	User   *User  `json:"user"`
	Zookie string `json:"zookie,omitempty"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (r *LoginRequest) GetEmail() string    { return r.Email }
func (r *LoginRequest) GetPassword() string { return r.Password }

// LoginResponse carries no Zookie — login is a read, not a write.
type LoginResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresIn    int64  `json:"expires_in"`
}

// ── User messages ─────────────────────────────────────────────────────────────

// GetUserRequest carries an optional Zookie.
// When Zookie is non-empty the repository performs a strong (non-BestEffort)
// read, guaranteeing the caller sees the commit the Zookie was issued for.
type GetUserRequest struct {
	Id     string `json:"id"`
	Zookie string `json:"zookie,omitempty"`
}

func (r *GetUserRequest) GetId() string     { return r.Id }
func (r *GetUserRequest) GetZookie() string { return r.Zookie }

// UpdateUserRequest carries optional field updates.
// Empty string means "not provided — do not update this field".
type UpdateUserRequest struct {
	Id        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Nickname  string `json:"nickname"`
	Country   string `json:"country"`
}

func (r *UpdateUserRequest) GetId() string        { return r.Id }
func (r *UpdateUserRequest) GetFirstName() string { return r.FirstName }
func (r *UpdateUserRequest) GetLastName() string  { return r.LastName }
func (r *UpdateUserRequest) GetNickname() string  { return r.Nickname }
func (r *UpdateUserRequest) GetCountry() string   { return r.Country }

type DeleteUserRequest struct {
	Id string `json:"id"`
}

func (r *DeleteUserRequest) GetId() string { return r.Id }

// DeleteUserResponse includes the Zookie of the write.
type DeleteUserResponse struct {
	Message string `json:"message"`
	Zookie  string `json:"zookie,omitempty"`
}

// ListUsersRequest carries an optional Zookie for consistent list reads.
type ListUsersRequest struct {
	Country  string `json:"country"`
	Page     int32  `json:"page"`
	PageSize int32  `json:"page_size"`
	Zookie   string `json:"zookie,omitempty"`
}

func (r *ListUsersRequest) GetCountry() string  { return r.Country }
func (r *ListUsersRequest) GetPage() int32      { return r.Page }
func (r *ListUsersRequest) GetPageSize() int32  { return r.PageSize }
func (r *ListUsersRequest) GetZookie() string   { return r.Zookie }

type ListUsersResponse struct {
	Users []*User `json:"users"`
	Total int32   `json:"total"`
	Page  int32   `json:"page"`
	Pages int32   `json:"pages"`
}

// UserResponse is returned by GetUser (read, no Zookie).
// UpdateUser uses WriteUserResponse to carry the write Zookie.
type UserResponse struct {
	User *User `json:"user"`
}

// WriteUserResponse is returned by UpdateUser; it carries the Zookie of
// the write so callers can anchor subsequent reads to this exact commit.
type WriteUserResponse struct {
	User   *User  `json:"user"`
	Zookie string `json:"zookie,omitempty"`
}

type User struct {
	Id        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Nickname  string `json:"nickname"`
	Email     string `json:"email"`
	Country   string `json:"country"`
	Active    bool   `json:"active"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

// ── Health messages ───────────────────────────────────────────────────────────

type HealthCheckRequest struct{}
type HealthCheckResponse struct {
	Status string `json:"status"`
	Time   string `json:"time"`
}
